- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update Repositories
      become: true
      ansible.builtin.package:
        update_cache: true     
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/gpg.yml
    - include_tasks: tasks/core-utils.yml
    - include_tasks: tasks/productivity.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/lnf.yml
