- name: Cloning dotfiles
  git:
    recursive: true
    repo: https://github.com/NChitty/dotFiles.git
    dest: "{{ lookup('env', 'HOME') }}/dotFiles"
    key_file: 
  tags:
    - install
    - dotfiles
- name: Assert Stow
  become: true
  ansible.builtin.package:
    name: "stow"
    state: "present"
- name: Stow dotfiles
  shell: cd $HOME/dotFiles && stow .
